parameters:
    nethesis_sms.sms.class: Nethesis\Service\SmsBundle\DependencyInjection\SmsService

services:
    nethesis_sms.sms:
        class: %nethesis_sms.sms.class%
#        arguments: [@service_id, "plain_value", %parameter%]
